heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: dimBaluev
      image: ubuntu-trusty
      flavor: m1.small
      networks:
        - network: local
      user_data: |
        #!/bin/bash
        sudo chsh -s /bin/bash ec2-user
        cd /home/ec2-user
        sudo apt-get update
        echo "install puppet git" >> /tmp/log
        sudo apt-get install -y puppet git
        echo "puppet module install aco-oracle_java" >> /tmp/log
        sudo puppet module install aco-oracle_java
        echo "puppet module install garethr-scala" >> /tmp/log
        sudo puppet module install garethr-scala
        echo "git clone https://github.com/baluevD/Puppet.git" >> /tmp/log
        git clone https://github.com/baluevD/Puppet.git
        echo "puppet apply Puppet/puppet.pp" >> /tmp/log
        sudo puppet apply Puppet/puppet.pp
        echo "git clone https://github.com/baluevD/actors.git" >> /tmp/log
        git clone https://github.com/baluevD/actors.git
